# Generated by Django 6.0 on 2025-12-18 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_tbl_placde'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tbl_placde',
            new_name='tbl_place',
        ),
    ]
