# Generated by Django 6.0 on 2026-01-05 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_tbl_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_number', models.CharField(max_length=50)),
            ],
        ),
    ]
