# Generated by Django 6.0 on 2026-01-05 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_tbl_ward'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(max_length=50)),
                ('worker_email', models.CharField(max_length=50)),
                ('worker_contact', models.CharField(max_length=50)),
                ('worker_photo', models.FileField(upload_to='Assets/AdminDocs/')),
                ('worker_password', models.CharField(max_length=50)),
                ('ward_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_ward')),
            ],
        ),
    ]
