# Generated by Django 6.0 on 2026-01-05 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_tbl_worker'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_worker',
        ),
    ]
