# Generated by Django 6.0 on 2026-01-06 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_delete_tbl_worker'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_wastecategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wastecategory_name', models.CharField(max_length=50)),
            ],
        ),
    ]
