# Generated by Django 6.0 on 2026-01-06 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0013_tbl_wastecategory'),
        ('Guest', '0011_tbl_worker'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_assignward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignward_date', models.DateField(auto_now_add=True)),
                ('ward_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_ward')),
                ('worker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_worker')),
            ],
        ),
    ]
