# Generated by Django 6.0 on 2026-01-06 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0011_tbl_worker'),
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_workerattendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workerattendence_datetime', models.DateField(auto_now_add=True)),
                ('workerattendence_status', models.IntegerField(default=0)),
                ('worker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_worker')),
            ],
        ),
    ]
