# Generated by Django 6.0 on 2026-02-02 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0002_tbl_workerattendence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_workerattendence',
            name='worker_id',
        ),
        migrations.DeleteModel(
            name='tbl_assignward',
        ),
        migrations.DeleteModel(
            name='tbl_workerattendence',
        ),
    ]
