# Generated by Django 6.0 on 2026-02-02 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0013_tbl_wastecategory'),
        ('Guest', '0016_tbl_worker'),
        ('worker', '0003_remove_tbl_workerattendence_worker_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_assignward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignward_date', models.DateField(auto_now_add=True)),
                ('ward_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_ward')),
                ('worker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_worker')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_workerattendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workerattendence_datetime', models.DateField(auto_now_add=True)),
                ('workerattendence_status', models.IntegerField(default=0)),
                ('worker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_worker')),
            ],
        ),
    ]
