# Generated by Django 6.0 on 2026-01-05 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0009_tbl_worker'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_worker',
        ),
    ]
