# Generated by Django 6.0 on 2026-01-07 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0011_tbl_worker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_user',
            name='place',
        ),
        migrations.RemoveField(
            model_name='tbl_user',
            name='user_gender',
        ),
    ]
