# Generated by Django 6.0 on 2026-01-07 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0012_remove_tbl_user_place_remove_tbl_user_user_gender'),
        ('User', '0003_remove_tbl_waste_user_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_user',
        ),
    ]
