# Generated by Django 6.0 on 2026-01-07 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_tbl_wastecategory'),
        ('Guest', '0013_delete_tbl_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=50)),
                ('user_contactno', models.CharField(max_length=50)),
                ('user_address', models.CharField(max_length=50)),
                ('user_password', models.CharField(max_length=50)),
                ('user_houseno', models.CharField(max_length=50)),
                ('user_photo', models.FileField(upload_to='Assets/UserDocs/')),
                ('user_status', models.IntegerField(default=0)),
                ('ward_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_ward')),
            ],
        ),
    ]
