# Generated by Django 6.0 on 2026-02-02 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0014_tbl_user'),
        ('worker', '0003_remove_tbl_workerattendence_worker_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_worker',
        ),
    ]
