# Generated by Django 6.0 on 2026-02-02 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0015_delete_tbl_worker'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_name', models.CharField(max_length=50)),
                ('worker_email', models.CharField(max_length=50)),
                ('worker_contact', models.CharField(max_length=50)),
                ('worker_address', models.CharField(max_length=50)),
                ('worker_photo', models.FileField(upload_to='Assets/workerDocs/')),
                ('worker_password', models.CharField(max_length=50)),
                ('worker_proof', models.FileField(upload_to='Assets/workerDocs/')),
                ('worker_status', models.IntegerField(default=0)),
                ('worker_latitude', models.CharField(max_length=50)),
                ('worker_longitude', models.CharField(max_length=50)),
            ],
        ),
    ]
