# Generated by Django 6.0 on 2026-02-02 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0016_tbl_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_worker',
            name='worker_curr_city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_worker',
            name='worker_latitude',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_worker',
            name='worker_longitude',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
