# Generated by Django 6.0 on 2026-01-07 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_tbl_wastecategory'),
        ('Guest', '0011_tbl_worker'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_waste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_date', models.DateField(auto_now_add=True)),
                ('waste_qty', models.IntegerField(default=0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
                ('wastecategory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_wastecategory')),
            ],
        ),
    ]
