# Generated by Django 6.0 on 2026-01-07 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_tbl_waste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_waste',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='tbl_waste',
            name='wastecategory_id',
        ),
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
        migrations.DeleteModel(
            name='tbl_waste',
        ),
    ]
