# Generated by Django 6.0 on 2026-01-07 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_waste',
        ),
    ]
